language: node_js
node_js:
  - iojs-v3.0
  - iojs-v2.0
  - iojs-v1.0
  - 16
  - 14
  - 12
  - 10
  - 8
  - 6
  - 4
  - 0.12
  - 0.10
script: "npm run test-travis"
after_script:
  - npm install codecov.io
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js
